config/routes.rb
Ipmanager::Application.routes.draw do
    resources :networks
    resources :devices
    resources :users
    resources :activities
    root :to => "Static#home"
    
    %w(admin export logout).each do |page|
        get page => "static##{page}"
    end
    

end

app/models/network.rb
class Network < ActiveRecord::Base
  require 'ipaddr'
  
  has_many :devices, :dependent => :restrict
  has_many :users, :dependent => :nullify
  has_and_belongs_to_many :buildings
  belongs_to :dhcp_server
  attr_accessible :mask, :network, :gateway, :dhcp_server_id, :vlan, :building_ids, :description
  
  def mask
    IPAddr.new(super,Socket::AF_INET).to_s
  end
  
  def network
    IPAddr.new(super,Socket::AF_INET).to_s
  end
  
  def description
    super.nil? ? "" : super
  end
  
  def gateway
    IPAddr.new(super,Socket::AF_INET).to_s
  end
  
  #displays mask "slash number" e.g. 255.255.255.0 is "24"
  def cidr_mask
    32-Integer(Math.log2((IPAddr.new(mask,Socket::AF_INET).to_i^0xffffffff)+1))
  end
  
  #displays n.n.n.n/n
  def cidr_full
    network+"/"+cidr_mask.to_s
  end
  
  #displays n.n.n.n/n description
  def cidr_and_description
    cidr_full+" "+description
  end
  
  #initializes IPs for a network if they have not been created yet
  def init_ips
    iprange = IPAddr.new(self.cidr_full).to_range
    iprange.each do |ip|
      # create all but the first and last ips in the range
      if (ip != iprange.first && ip != iprange.last)
        self.devices.find_or_create_by_ip(:ip => ip.to_i)
      end
    end
  end
  
  def updatehostnames
    #we need two different strings
    #one being the reverse zone name, down to class-b-specificity
    #the second being a class-c list of ip's for grep
    
    #reverse zones exist on a class b level, but we only want to get info for
    #devices on a class c level, so we need to build a string to grep for those only
    #we need to loop through which class c's we need.
    #for example, 140.254.248.0/23 is axfr'd with 254.140.in-addr.arpa
    #and needs to be grepped with 248.254.140 and 249.254.140
    n = IPAddr.new(self.network+"/"+self.mask)
    reverse = n.reverse.split(/\./)
    #remove the first 2 octets
    reverse_zone = reverse.clone
    reverse_zone.shift(2)
    reverse_zone = reverse_zone.join '.'
    
    reverse_class_b = reverse.clone
    reverse_class_b.shift(2)
    reverse_class_b.pop(2)
    reverse_class_b = reverse_class_b.join '\.'
    first_third_octet = n.to_range.first.to_s.split(/\./)[2].to_i
    last_third_octet = n.to_range.last.to_s.split(/\./)[2].to_i
    
    reverse_grep = Array.new
    
    for i in first_third_octet..last_third_octet do
      reverse_grep.push(i.to_s + '\.' + reverse_class_b)
    end
    
    #example dig|grep command: dig axfr 254.140.in-addr.arpa | grep -e "248\.254\.140\|249\.254\.140"
    dig = `dig axfr #{reverse_zone} | grep -e \"#{reverse_grep.join '\\|'}\"`
    unless dig.empty?
      dig.split(/\n/).each do |line|
        
        #parse out ip address and hostname
        matchdata = /(?<reverseip>[\d\.]+)\.in\-addr\.arpa\.\s+\d+\s+IN\s+PTR\s+(?<fqdn>[\w\-\.]+)\./.match(line)
        
        #convert parsed out ip address to integer form
        ip = IPAddr.new(matchdata[:reverseip].split(/\./).reverse.join('.'),Socket::AF_INET).to_i
        
        device = devices.find_by_ip(ip)
        unless device.nil?
          device[:hostname] = matchdata[:fqdn]
          device.save
        end
      end
    else
      puts "Zone transfer failed"
    end
  
  end
  
  #gets array of network addresses that are unique by the first 2 octets
  def self.uniq_class_b
    networks = Array.new
    ActiveRecord::Base.connection.select_all('select DISTINCT (network & 0xffff0000) as network from networks order by network').each do |n|
      networks.push(IPAddr.new(n['network'].to_i,Socket::AF_INET).to_s)
    end
    networks
  end
  
  #gets all networks that match the provided class b address
  def self.find_by_class_b(address)
    #handle empty address
    if address.nil? || address.empty?
      return Network.all
    end
      
    address_i = IPAddr.new(address,Socket::AF_INET).to_i
    network_ids = Array.new
    ActiveRecord::Base.connection.select_all("select id from networks where (#{address_i} & 0xffff0000) = (network & 0xffff0000)").each do |n|
      network_ids.push(n['id'])
    end
    
    begin
      Network.find(:all, :conditions => {:id => network_ids})
    rescue
      Network.all
    end
    
  end
  
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  require 'ipaddr'
  respond_to :js, :html, :xls
  
  def index
    respond_to do |format|
      #for xls, we actually want to export all devices from all networks
      format.xls do
        book = Spreadsheet::Workbook.new
        Network.all.each do |n|
          sheet = book.create_worksheet
          sheet.name = n.cidr_and_description
          ToXls::Writer.new(n.devices, :columns => [:ip, :description, :type => [:name]], :headers => %w{IP Description Type}).write_sheet(sheet)
        end
        data = StringIO.new
        book.write(data)
        send_data data.string, :type => 'application/excel', :disposition => 'attachment', :filename => 'networks.xls'
      end
    end
  end
  
  def show
    begin
      if params.has_key?(:building_id) && !params[:building_id].empty?
        @networks = Building.find(params[:building_id]).networks
        @network = @networks.first
        @building_id = params[:building_id]
      elsif params.has_key?(:network_class_b) && !params[:network_class_b].empty?
        @networks = Network.find_by_class_b(params[:network_class_b])
        @network = @networks.first
        @class_b = params[:network_class_b]
      else
        @networks = Network.all
        @network = Network.find(params[:id])
      end
      @network.updatehostnames
    rescue
      @networks = Network.all
      @network = Network.first
    end

    
    respond_to do |format|
      format.js do
      end
      format.html do
      end
    end
  end
  
  def new
    
  end
  
  def edit
    @network = Network.find(params[:id])
  end
  
  def update
    @network = Network.find(params[:id])
    params[:network][:gateway] = IPAddr.new(params[:network][:gateway],Socket::AF_INET).to_i
    
    if @network.update_attributes(params[:network])
      #build update string for activity log
      Activity.create(:activity => "Updated Network #{@network.cidr_full},
        Description: #{@network.description},
        Buildings: #{@network.buildings.pluck(:name).join(', ')}",
        :user_id => User.find_by_name_n(current_user.name_n))
      
      redirect_to :action => 'show', :id => @network
    else
      redirect_to :action => 'edit', :id => @network
    end
  end
  
  def destroy
    @network = Network.find(params[:id])
    @network.devices.destroy_all
    @network.buildings.destroy_all
    @network.destroy
    
    redirect_to :action => 'show', :id => Network.first
  end
  
end

app/helpers/network_helper.rb
module NetworkHelper
end

app/views/networks/edit.html.erb
<p>Editing <%= @network.cidr_full %></p>

<%= form_for @network do |n| %>
  Description: <%= n.text_field :description %>
  <br>
  Gateway: <%= n.text_field :gateway, :value => n.object.gateway %>
  <br>
  DHCP Server: <%= collection_select(:network, :dhcp_server_id, DhcpServer.all, :id, :name) %>
  <br>
  VLAN: <%= n.text_field :vlan %>
  <br>
  Buildings: <%= collection_select(:network, :building_ids, Building.all, :id, :name, {:selected => @network.buildings.pluck(:building_id)}, :multiple => true) %>
  <br>
  <%= submit_tag "Save" %> <%= link_to "Delete", network_path(@network), :confirm => "Are you sure?", :method => :delete %>
<% end %>

app/views/networks/index.html.erb
<script type='text/javascript'>
  $(document).ready(function(){
    $("#network_id").change(function(evt){
      window.location.href = "/networks/"+this.value;
    });
  });
</script>
<%= form_tag("/networks", :method => 'get') %>
<%= collection_select('network','id',Network.all,:id,:network) %>

app/views/networks/show.html.erb
<script type='text/javascript'>
  $(document).ready(function(){
    $("#network_filter_form > form > select").on('change',function(evt){
      document.location.href = "<%= networks_path %>/"+$("#network_id").val()+(this.id == 'network_id' ? "" : "?"+this.id+"="+this.value);
    });
  });
</script>
<div id='network_filter_form'>
<%= form_tag(networks_path, :method => 'get') do -%>
Subnet: <%= collection_select(:network, :id, @networks, :id, :cidr_and_description) %>
Building: <%= collection_select(:building, :id, Building.all, :id, :name, {:prompt=>"All Buildings", :selected => @building_id}) %>
Network: <%= select_tag("network_class_b", options_for_select(Network.uniq_class_b, {:selected => @class_b}), {:prompt=>"All Class B's"}) %>
<% end -%>
</div>

<div id="network_info_area">
    <ul>
        <li><b>Subnet: </b><%= @network.cidr_full %></li>
        <li><b>Mask: </b><%= @network.mask %></li>
        <li><b>Gateway: </b><%= @network.gateway %></li>
        <li><b>DHCP: </b><%= @network.dhcp_server.nil? ? 'Unknown' : @network.dhcp_server.name %></li>
        <li><b>VLAN: </b><%= @network.vlan.nil? ? 'Unknown' : @network.vlan.to_s %></li>
        <li><b>Building: </b><%= @network.buildings.pluck(:name).join(', ') %></li>
    </ul>
    <%= link_to("Edit", edit_network_url(@network.id)) %>
</div>
<br />
<table>
<tr>
    <th>IP</th>
    <th>Hostname</th>
    <th>Description</th>
    <th>Type</th>
    <th>Last Updated</th>
    <th>Edit</th>
</tr>
<% @network.devices.all.each do |device| %>
    <tr>
        <td><%= device.ip %></td>
        <td><%= device.hostname %></td>
        <td><%= device.description %></td>
        <td><%= device.type.nil? ? "" : device.type.name %></td>
        <td><%= device.updated_at.strftime("%Y/%m/%d") %></td>
        <td><%= link_to "Edit", edit_device_path(device) %></td>
    </tr>
<% end %>
</table>

app/views/networks/show.js.erb
$("#network_id").html("<%= j(collection_select(:network,:id,@networks,:id,:cidr_and_description, :selected => @network.id)) %>");